constexpr byte	PlayerSprite		= 0;				// Player sprite starting number
constexpr byte	PlayerSpritePattern	= 0x24;				// Player sprite starting pattern
constexpr byte	PlayerSpriteColor	= 8;				// Player sprite color
constexpr byte	PlayerStartX		= (256 - 16) / 2;	// Player start position
constexpr byte	PlayerStartY		= 180;
constexpr byte	ClawYOffset			= 4;				// Claw offset
constexpr byte	MinPlayerLeft		= 0;				// Minimum player left
constexpr byte	MaxPlayerRight		= 256 - 16;			// Maximum player right
constexpr byte	MoveSpeed			= 1;				// Move speed per frame
constexpr byte	AnimationDelay		= 6;				// Animation delay
constexpr byte	AnimationFrames		= 3;				// Animation frames
